# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
